# Generated by Django 4.2 on 2023-06-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Order',
        ),
    ]
