# Generated by Django 4.2 on 2023-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
