# Generated by Django 4.2 on 2023-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(default=0, max_length=111),
        ),
    ]
