# Generated by Django 4.2 on 2023-06-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_order_address2_alter_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
    ]
