# Generated by Django 4.2 on 2023-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_address1_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemJson',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
