# Generated by Django 4.2 on 2023-06-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orderupdate_alter_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_Id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
