# Generated by Django 4.2 on 2023-06-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_orderupdate_order_id_orderupdate_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodOrder',
            fields=[
                ('itemJson', models.CharField(default='', max_length=5000)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(default=0)),
                ('zip_code', models.IntegerField(default=0)),
            ],
        ),
    ]
