# Generated by Django 4.2 on 2023-06-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_prodorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prodOrder',
        ),
    ]
