# Generated by Django 4.2 on 2023-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemJson', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
