# Generated by Django 4.2 on 2023-07-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_Update',
            field=models.CharField(default='', max_length=200),
        ),
    ]
