# Generated by Django 4.2 on 2023-07-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order_time_order_order_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
