# Generated by Django 4.2 on 2023-07-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_Time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='Time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
