# Generated by Django 4.2 on 2023-08-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
