# Generated by Django 4.2 on 2023-08-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_address_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='newAddress',
            fields=[
                ('ordId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
