# Generated by Django 4.2 on 2023-08-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_newaddress_city_newaddress_name_newaddress_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
