# Generated by Django 4.2 on 2023-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaddress',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
